name: Build and Publish pg_featureserv Docker Image

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout code
            - name: "Checkout GitHub Action"
              uses: actions/checkout@v3

            # Step 2: Set up Docker Buildx for multi-platform support
            - name: "Set up Docker Buildx"
              uses: docker/setup-buildx-action@v2

            # Step 3: Log in to GitHub Container Registry
            - name: "Login to GitHub Container Registry"
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build the Docker image
              run: |
                  make APPVERSION=1.3.1 TARGETARCH=amd64 clean multi-stage-docker
                  docker tag usace/pg_featureserv:1.3.1-amd64 ghcr.io/${{ github.repository }}:1.3.1-amd64
                  docker tag usace/pg_featureserv:1.3.1-amd64 ghcr.io/${{ github.repository }}:latest
                  docker push ghcr.io/${{ github.repository }}:1.3.1-amd64
                  docker push ghcr.io/${{ github.repository }}:latest
