name: Build and Publish pg_featureserv Docker Image

on:
    push:
        branches: ["master"] # Runs on direct push to master branch
    pull_request:
        branches: ["master"]
        types: [closed] # Runs only when a PR to master is closed
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        # Set permissions for GITHUB_TOKEN
        permissions:
          packages: write

        steps:
            # Step 1: Checkout code
            - name: "Checkout GitHub Action"
              uses: actions/checkout@v3

            # Step 2: Set up Docker Buildx for multi-platform support
            - name: "Set up Docker Buildx"
              uses: docker/setup-buildx-action@v2

            # Step 3: Log in to GitHub Container Registry
            - name: "Login to GitHub Container Registry"
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Step 4: Only continue if the PR was merged (for PR-based triggers)
            - name: "Check if PR was merged"
              if: github.event.pull_request.merged == true
              run: echo "PR was merged. Proceeding with build."

            # Step 5: Skip if PR was closed without merging
            - name: "Abort if PR was closed without merging"
              if: github.event.pull_request.merged != true
              run: |
                  echo "PR was closed without merging. Skipping build."
                  exit 0  # Exits early, preventing further steps

            # Step 6: Build and Push Docker image (Only runs if PR was merged or direct push)
            - name: Build the Docker image
              run: |
                  make APPVERSION=1.3.1 TARGETARCH=amd64 clean multi-stage-docker
                  docker tag usace/pg_featureserv:1.3.1-amd64 ghcr.io/${{ github.repository }}:1.3.1-amd64
                  docker tag usace/pg_featureserv:1.3.1-amd64 ghcr.io/${{ github.repository }}:latest
                  docker push ghcr.io/${{ github.repository }}:1.3.1-amd64
                  docker push ghcr.io/${{ github.repository }}:latest
